#!/usr/bin/env python3
import subprocess

from colorama import Fore
import os
import socket
import random
import argparse
import requests



s = socket.socket()
s.settimeout(3)

#variables
ips = []
ip = ''
ports = []
port_info = ''
current_open = ''
hostname = ''
parser = argparse.ArgumentParser()

discord_webhook_url = 'https://discordapp.com/api/webhooks/925840344095006822/SK8qJiWvd7v8ufsMJARCKyVAWyioQ4Jwii_Qe_8EKzWoREUNBXO3puu9hnNcwSWYissW'


#arguments
parser.add_argument('--verbose' , "-v",help="Verbose (prints every action (Usefull for debugging))" , action="store_true")
parser.add_argument('--ports' , "-p",help="Select Ports" , action="store_true")
parser.add_argument('--search' , "-s",help="Searches logs for IPs with open ports" , action="store_true")
parser.add_argument("port", type=str, help="Ports (seperate each one with a comma -p 80,443,21 |Default ports are 1-1000)", nargs='?')
parser.add_argument('--webhook' , "-w",help="Send Open Ports On An Ip To A Discord Webhook" , action="store_true")
parser.add_argument("webhook_url", type=str, help="Discord Webhook Link", nargs='?')


args = parser.parse_args()

#creating scans directory
if not os.path.exists('~/scans'):
    os.system('mkdir ~/scans')

if not args.ports:
    for i in range(1000):
        ports.append(i)



#changing variables according to arguments
if args.ports:
    ports = []
    try:
        ports = args.port.replace(',',' ')
        ports = (ports.split())
        ports = list(map(int, ports))
    except Exception as e:
        print(e)
        print(f'{Fore.RED}No Arguments given for --ports')
    if not args.search:
        print(f"Scanning Ports {' '.join(str(e) for e in ports)}")
    elif args.search:
        print(f"All Found Records Of Port/s {' '.join(str(e) for e in ports)}" )


#searches through the ip logs for open ports
def search_ips():
    if args.search:
        if args.ports:
            for port in ports:
                try:
                    os.system(f'cat ~/scans/* |grep "Port {port} is open for " ')
                except Exception as e:
                    print(e)
                    print(f'Could Not Find {os.getenv("HOME")}/scans')
        else:
            try:
                os.system(f'cat ~/scans/* |grep " is open for " ')
            except Exception as e:
                print(e)
                print(f'Could Not Find {os.getenv("HOME")}/scans')
    exit()





#find valid IPs
def find_ip():
    global ip
    ip = []
    for i in range(4):
        ip.append(str(random.randint(0,255)))
    ip = '.'.join(ip)








#scans the selected ports of the valid IPs
def scan(ip):

    global webhook_content
    global port_info
    global current_open
    webhook_content = ''
    port_info = ''
    current_open = []
    port_list = ['']
    for port in ports:
        if args.verbose:
            print(f'Scanning Port {port}',end='\r')

        try:
            address = (f"{ip}", port)
            check_if_open = s.connect_ex(address)
            if check_if_open  == 0:
                print(port)

                if args.verbose:
                    print(f'{Fore.GREEN} OPEN {Fore.WHITE}', end = '\r')

                hostname = socket.gethostbyaddr(ip)
                current_open.append(port)
                print(f'\n\n\n Current open = {current_open} \n\n\n\n')

                port_info += (f"{Fore.GREEN} Port {port} is open for {ip} {hostname[0]} {Fore.WHITE}\n\n")


                print(socket.gethostbyaddr(ip))
            else:
                if args.verbose:
                    print(f'{Fore.RED} CLOSED {Fore.WHITE}')


                port_info += (f"{Fore.RED}Port {port } is not open for {ip} {Fore.WHITE}\n\n")


            for porter in current_open:
                webhook_content = (f"{current_open} is open for {ip}      ")
                #dunno why i called it porter lmao

        except Exception as e:
            port_info += (f'{port} Couldnt Connect: {e}\n')
            continue



# logs the ips along with the valid ports
def log_ip(ip):
    scan('google.com')
    os.system(f'touch ~/scans/{ip}_{current_open}------{hostname}')

    f = open(f"{os.getenv('HOME')}/scans/{ip}", "a")

    f.write(str(port_info))
    print(f'Writen to file ~/scans/{ip}')
    f.close()
    print('Found web hook parameter')
    if args.webhook:
        print(ip , webhook_content)



        webhook = {
            "content": f"Here Is The Scan Result: ```{webhook_content}```",

        }

        requests.post(discord_webhook_url, data=webhook)
        print(webhook)

        print('sent')

    ips.append(ip)


#checks the host is up
def check_ip(ip):
    response = bool
    try:
        subprocess.check_output(["ping", "-c", "1", '-w 1',ip])
        response = True
    except subprocess.CalledProcessError:
        response = False

    if response:
        print(f'({Fore.GREEN}+{Fore.WHITE}) {ip} is an IP')
        log_ip(ip)



    elif not response:
        print(f'({Fore.RED}-{Fore.WHITE}) {ip} is not an IP')

#runs all the code
def main():
    if args.search:
        search_ips()

    find_ip()
    check_ip(ip)
    main()


if __name__ == '__main__':

    main()


